name: Component / WIT

on:
  push:
    tags:
    - 'component-wit-v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for softprops/action-gh-release
      packages: write # for publishing the wit to ghcr.io
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Extract tag context
      id: ctx
      run: |
          version=${GITHUB_REF_NAME#wit-v}
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "tarball=wit-${version}.tar.gz" >> "$GITHUB_OUTPUT"
          echo "version is ${version}"
    - uses: taiki-e/install-action@8484225d9734e230a8bf38421a4ffec1cc249372
      with:
        tool: wash-cli@0.36.1
    - name: Generate and set config
      shell: bash
      env:
        OCI_USERNAME: ${{ github.repository_owner }}
        OCI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cat << EOF > package_config.toml
        [namespace_registries]
        wasmcloud = "wasmcloud.com"
        wrpc = "bytecodealliance.org"
        wasi = "wasi.dev"

        [registry."wasmcloud.com".oci]
        auth = { username = "${OCI_USERNAME,,}", password = "${OCI_PASSWORD}" }
        EOF
        echo "WASH_PACKAGE_CONFIG_FILE=$(realpath package_config.toml)" >> $GITHUB_ENV
    - name: Build
      run: |
        wash wit build --wit-dir ./component/wit -f package.wasm
    - name: Push version-tagged WebAssembly binary to GHCR
      run: |
        wash wit publish package.wasm
    - name: Package tarball for release
      run: |
        tar -cvzf ${{ steps.ctx.outputs.tarball }} -C ./component wit
    - name: Release
      uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048
      with:
        files: ${{ steps.ctx.outputs.tarball }}
        make_latest: "false"
