name: Go

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/provider-go.yaml'
      - 'provider/**'
      - 'examples/provider/**'
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/provider-go.yaml'
      - 'provider/**'
      - 'examples/provider/**'

env:
  GOLANGCI_VERSION: "v1.61"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ./provider
          - ./examples/provider/http-server
          - ./examples/provider/keyvalue-inmemory

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ matrix.module }}/go.mod"

      - name: Build
        run: go build -C ${{ matrix.module }} -v ./...

      - name: Test
        run: go test -C ${{ matrix.module }} -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./provider/go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          working-directory: ./provider

